name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest changes
      uses: actions/checkout@v4
      
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        
    - name: Lint the code
      run: if [[ $(gofmt -l . | wc -l) > 0 ]]; then exit 1; fi

    - name: Run the tests
      run: go test -v ./...
